#env:
#  global:
#    - CC_TEST_REPORTER_ID=
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
sudo: false
#before_script:
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm test
#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT